--- 
- hosts: s1-3
  tasks:
  - name: print stdout stderr
    command: echo "hello there"
    register: hello
  - debug: 
       msg: "stdout={{ hello.stdout }}"
  - debug: 
       msg: "stderr={{ hello.stderr }}"
  - debug:
      msg: "System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"
