---  
- hosts: s3
  #gather_facts: no
- name: Add users
  user:
    name=test1
    system=no
    shell=/bin/bash
    append=yes
    #groups={{ item.group  }}
    # this is just a default password, I think it's SHA512 for "changeme"
    #     password=$6$rounds=656000$iO7Q9L6/w8dUUQVf$rmtnxrQ15TGAfG5ODxQ/WGyEpTwk.vD1W.UtedmOlo9YNkrIwapYMjmKmteEnUJmRYucgUVxXUQy7gtenpLmw0
    #         update_password=on_create
    #           when: item.group is defined
    #             with_items: users
    #
