--- 
- hosts: s1-3
  become: true 
  tasks:
  - name: create user nesaadm
    user: 
      state: present
      name: nesaadm
      #password: "{{ 'password' | password_hash('sha512') }}"
      shell: /bin/bash
