--- 
- hosts: s3
  #become: true
  tasks:
  - name: show user in file command 
    command: cat /etc/passwd
    #shell: cat /etc/passwd | grep nesaadm
  - name: show user in file shell
    #command: cat /var/log/messages
    shell: cat /etc/passwd
    #        #shell: cat /etc/passwd | grep nesaadm  
