---
- hosts: s6
  become: true
  tasks:
  - name: remove user nesaadm
    user:
      name: nesaadm
      state: absent
      remove: yes
      #password: "{{ 'password' | password_hash('sha512') }}"
      #shell: /bin/bash

